/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package POE_part1;

import static org.junit.Assert.*;
import org.junit.Test;


public class AppTest {
    Login login = new Login();


   @Test
    public void testCheckUserName() {
        assertTrue(login.checkUserName("kyl_1"));
        assertFalse(login.checkUserName("kyle!!!!!!!"));
    }


   @Test
    public void testCheckPasswordComplexity() {
        assertTrue(login.checkPasswordComplexity("Ch&&sec@ke99!"));
        assertFalse(login.checkPasswordComplexity("password"));
    }


   @Test
    public void testRegisterUser() {
        assertEquals("User registered successfully.", login.registerUser("kyl_1", "Ch&&sec@ke99!", "Kyle", "Masenya"));
        assertEquals("Username is not correctly formatted, please ensure that your username contains an underscore and is no more than 5 characters in length.", login.registerUser("kyle!!!!!!!", "Ch&&sec@ke99!", "Kyle", "Masenya"));
        assertEquals("Password is not correctly formatted, please ensure that the password contains at least 8 characters, a capital letter, a number and a special character.", login.registerUser("kyl_1", "password", "Kyle", "Masenya"));
    }


   @Test
    public void testLoginUser() {
        User user = new User("kyl_1", "Ch&&sec@ke99!", "Kyle", "Masenya");
        assertTrue(login.loginUser("kyl_1", "Ch&&sec@ke99!", user));
        assertFalse(login.loginUser("kyl_1", "password", user));
    }


   @Test
    public void testReturnLoginStatus() {
        User user = new User("kyl_1", "Ch&&sec@ke99!", "Kyle", "Masenya");
        assertTrue(login.returnLoginStatus(true, user).startsWith("Welcome"));
        assertTrue(login.returnLoginStatus(false, user).startsWith("Username or password"));
    }
}
